module.exports = {
  preset: "ts-jest",
  testEnvironment: "node",
  roots: ["<rootDir>/tests"],
  setupFiles: ["<rootDir>/tests/setup/jest.setup.ts"],
  testMatch: ["**/__tests__/**/*.ts", "**/?(*.)+(spec|test).ts"],
  transform: {
    "^.+\\.ts$": "ts-jest",
  },
  collectCoverageFrom: [
    "controllers/**/*.ts",
    "services/**/*.ts",
    "repositories/**/*.ts",
    "middleware/**/*.ts",
    "utils/**/*.ts",
    "core/**/*.ts",
    "!**/*.d.ts",
    "!**/*.test.ts",
    "!**/*.spec.ts",
  ],
  coverageDirectory: "coverage",
  coverageReporters: ["text", "lcov", "html", "json"],
  coverageThreshold: {
    global: {
      branches: 60,
      functions: 60,
      lines: 60,
      statements: 60,
    },
  },
  setupFilesAfterEnv: ["<rootDir>/tests/setup/jest.setup.ts"],
  testTimeout: 30000,
  maxWorkers: "50%",
  detectOpenHandles: true,
  forceExit: true,
  verbose: true,
};
